### ISSUE TITLE
library prints to stdout/err

### ISSUE THREAD

**Issue by x42** [agfline/LibAAF#4]
It is bad practice for a library to print to stdout/stderr.

Say you write an application that can directly to output to stdout. This will not be possible if any shared library will also produce output there.

Common practice is to either only optionally enable debug messages for the shared-lib, or alternatively add a logger callback. Then the  front-end application could set a log callback to receive any messages.

**Comment by x42** [comment]
Great to hear that it's already on your list!
and no, it  is not high priority, I have just reported it so that it won't be forgotten.

**Comment by johne53** [comment]
Could this get solved by building libaaf as a static library, rather than a dynamic one (the printouts would then be coming from the relevant executable...)

I haven't reached the stage yet of creating a **libaaf** build project for MSVC but I must admit, I'd been considering whether to use the static build model anyway, for other reasons.

**Comment by johne53** [comment]
> 
> I haven't reached the stage yet of creating a **libaaf** build project for MSVC

I might give this a try during the weekend. @agfline - could you maybe give me a list of which of your 'C' files I'll need when building libAAF?

**Comment by agfline** [comment]
I finally implemented that callback function to handle debug and logging.
Everything should be up to date now, on both Ardour and libaaf side.

**Comment by johne53** [comment]
Thanks Adrien - with regard to your **aaf** branch in Ardour, I think you forgot to add the new **debug.c** file.

**Comment by agfline** [comment]
Thanks John.
Don't know if you get notified when I commit. So just in case, it's fixed ;)

**Comment by johne53** [comment]
@Robin - back in the old ArdourXchange days I used to generate session names based on the name of the supplied AAF file. So if the filename was **ABcde.aaf**, the session would be called **ABcde.ardour**

But @Adrien finds the name by extracting it from the AAF file and I've come across one file where the session name is **"Coros LO "** (notice that the last character is a space character...)  When generating a sub-folder for the interchange files, it then tries to use a name ending in a space character - which fails on Windows because directories aren't allowed to end in a space character. It then occurred to me that the internal name might conceivably contain other invalid characters, such as a colon.

I'm pretty sure that Ardour already contains a function for validating file names but I'm not sure if it knows about the fact that directories can't end in a space. Can you remind me what's the name of that function (so I can check) ?

**Comment by agfline** [comment]
I did actually made some quick and dirty cleaning of the AAF composition name, but only for the cache folder and not for Ardour session.

https://github.com/agfline/ardour_aaf_support/blob/dcd3ae34066fe071975a74ab29f020612682a3ee/session_utils/new_aaf_session.cc#L844-L860

I didn't know about this windows rule. If Ardour has a proper function for cleaning file names I'll go with it, otherwise I'll improve my code.

**Comment by agfline** [comment]
I did actually made some quick and dirty cleaning of the AAF composition name, but only for the cache folder and not for Ardour session.

https://github.com/agfline/ardour_aaf_support/blob/dcd3ae34066fe071975a74ab29f020612682a3ee/session_utils/new_aaf_session.cc#L844-L860

I didn't know about this windows rule. If Ardour has a proper function for cleaning file names I'll go with it, otherwise I'll improve my code.

**Comment by agfline** [comment]
I did actually made some quick and dirty cleaning of the AAF composition name, but only for the cache folder and not for Ardour session.

https://github.com/agfline/ardour_aaf_support/blob/dcd3ae34066fe071975a74ab29f020612682a3ee/session_utils/new_aaf_session.cc#L844-L860

I didn't know about this windows rule. If Ardour has a proper function for cleaning file names I'll go with it, otherwise I'll improve my code.

**Comment by johne53** [comment]
I discovered 'ARDOUR::legalize_for_path()' and also 'ARDOUR::legalize_for_universal_path()' which both look at the supplied string and replace any illegal characters with an underscore. But for Windows use, I'm wondering if 'ARDOUR::legalize_for_path()' should also be converting any colon characters, if found. And in both cases (again for Windows use) they should maybe replace the last character with an underscore if the last character happens to be a space? Needs some thinking about, I guess :-(

Maybe it'd be safer if Adrien could use the older system (as in ArdourXchange) which utilized the supplied filename, rather than interrogating the AAF file to find a name. At least that way, the name would be guaranteed to be valid for the given platform. In fact, I think I used that method because the internal name was often "**Untitled**".

**Comment by agfline** [comment]
I made a [clean_filename()](https://github.com/agfline/LibAAF/blob/06a63a6b13580e6c55276a612bee3ca62ba0fbd0/src/common/utils.c#L174-L209) function which also replace last character in case it's a space or a dot.

Regarding AAF specification, the composition Mob::Name should identify the composition (that is, the timeline, project or session name, depending on software) and this was confirmed by all the files I've been testing so far.

The normal **new_aaf_session** behavior is to stick to that composition name and fallback to the AAF file name in case its empty. You also have an option to force session name to whatever you want using `--session-name`.

I just modified this option so you can force using the AAF file name : `--session-name AAFFILE` (AAFFILE is a keyword, do not replace it with your file name)

**Comment by johne53** [comment]
Thanks Adrien. I updated this morning and things are much better now. There's a small build issue in lines like this that you've added to 'utils.c':-

    switch ( c ) {

      case L'à':
      case L'á':
      case L'â':
      case L'ã':
      case L'ä':

MSVC doesn't like the 'L' macro here (possibly because 'c' is already in wchar format?) but it compiles okay with Clang. And the really good news is that these changes have fixed quite a few AAF files here which previously weren't importing. In fact I've only one AAF file now which won't import. It generates the audio clips okay and then crashes while trying to create the first track:-

    [i] new_aaf_session.cc : main() on line 1301 : Source file '865_2287_01_2' successfully imported to session.
    [i] new_aaf_session.cc : main() on line 1301 : Source file '865_2287_01_1' successfully imported to session.
    [i] new_aaf_session.cc : main() on line 1301 : Source file '865_2287_01' successfully imported to session.
    [i] new_aaf_session.cc : prepare_audio_track() on line 585 : Track number 0 (Track 5) does not exist. Adding new track.
          ^ ^ ^ CRASHES AFTER PRINTING THE ABOVE LINE ^ ^ ^

It's quite a small AAF file (28MB) so possibly email-able? Should I try and email it to you?

**@x42** - you and Paul will need to start considering how to integrate this for users. It's currently implemented as a console app with a large number of command-line options so my gut feeling is that it'll be too confusing for users. Maybe a dedicated Ardour dialog along the lines of **Session->Import PT session**?

**Comment by agfline** [comment]
Good news. Of course John, send me your file so I can look at it ;)

> There's a small build issue in lines like this that you've added to 'utils.c'

I'll comment this out, there is finally no use for this function.

For my part, [I still need some help to implement track levels / pan into Ardour](https://github.com/agfline/LibAAF/issues/5#issuecomment-1641070262). In the meantime, I'm doing code review and cleanup. A few major improvements to come with low level AAF parsing, those will require some testing on windows to ensure there is no drawback.

We're getting close !

**Comment by johne53** [comment]
I've just sent you a zipped up version of the problematic AAF file although it was still pretty big - so check your spam folder if you don't receive it.

**Comment by agfline** [comment]
Problem fixed.
libAAF and Ardour are up to date.

**Comment by johne53** [comment]
Well done Adrien - all my AAF files here are importing correctly now!!

Let me know when you've completed your low-level changes and I'll be happy to re-test the AAF's here.

**Comment by agfline** [comment]
> Let me know when you've completed your low-level changes and I'll be happy to re-test the AAF's here.

Well, you already have ! I pushed the low-level changes before the fix for your file ;) So everything is looking good.

Until we add support for track level / pan, I'll keep on doing code review and cleanup. I will also make more lightweight copyright-free test files for the test.sh script.

Thank you John for your time and efforts ;)

**Comment by johne53** [comment]
Yes I re-checked my AAF files here and they're all still importing correctly. So hopefully Paul and Robin can start thinking about the UI and integration features once they get some time. And it'd be nice to accommodate your progress log if poss.

**Comment by johne53** [comment]
Yea a log file for the last import could be helpful at times - but for normal use, it'd be good to display some simplified feedback during each import. It's very reassuring for users just to see the various clip names / tracks etc as they're each getting processed.

And we've now gone full circle (going back to Robin's first post...) as all this will eliminate the need to be printing stuff to stdout !!

**Comment by agfline** [comment]
So all the normal user logging (stderr/stdout) should be produced by Ardour itself (importing audio file, creating track, etc.). That is already the case in **new_aaf_session.cc**. 
And all the library-side log should be written to the file. I will make a callback for it in **new_aaf_session.cc**.

**Comment by x42** [comment]
> @x42 - you and Paul will need to start considering how to integrate this for users.

The eventual goal is to integrate it like Pro Tools import.  *Menu > Session > Import AAF* will **add** the aaf to the existing session.

**Comment by x42** [comment]
> Maybe you guys have a .clang-format file ?

Yes, we do. copy or symlink  `tools/clang-format`

**Comment by x42** [comment]
I consider this issue completed. Perhaps that discussion should continue elsewhere?

**Comment by johne53** [comment]
> 
> The eventual goal is to integrate it like Pro Tools import. _Menu > Session > Import AAF_ will **add** the aaf to the existing session.

Whenever you've time, is there some way you could work with @agfline to create (initially) a simplified import dialog - i.e. so we can at least make something available for beta testing?

I mentioned in https://github.com/agfline/LibAAF/issues/5#issuecomment-1657100629 that libaaf is working now in Mixbus as well as Ardour and I'm pretty sure there'd be Mixbus users willing to help test AAF.

**Comment by agfline** [comment]
The AAF import should work without any specific dialog, just by selecting the AAF file. However, we should consider to make a specific import dialog in the future with a few options, especially the ability for the user to select a directory that contains external audio files.

**Comment by johne53** [comment]
I think what Robin's saying is that an import window is needed, similar to what's already available when importing from Pro Tools (i.e. users are already familiar with that workflow). And he's recommending that the style of import should match the PT import style - where new tracks get added to an already loaded session, rather than creating a whole new session each time.

So  in addition to **create_new_session()** we'd need an extra function called something like **import_into_session()**

Maybe one of us should create a new thread where we can start suggesting the steps needed so we can get to the stage of making this beta-testable?

**Comment by x42** [comment]
> And he's recommending that the style of import should match the PT import style

Yes, I was really just thinking of a file-select dialog to get the ball rolling.  Fancy import options dialog can come later.

**Comment by johne53** [comment]
New thread started [here](https://github.com/agfline/LibAAF/issues/7)

**Comment by agfline** [comment]
[ardour_aaf_support](https://github.com/agfline/ardour_aaf_support) is currently up to date with libAAF, and code was cleaned up with Ardour's `clang-format` file.
